misc:
  gpu_mode: True
  verbose: True
  verbose_freq: 100
  snapshot_freq: 1
  exp_dir: indoor
  pretrain: ''
  dir: /home/scv6267/run/superglue_sift_results/
  mode: train

model:
  num_gpus: 1
  dataset: indoor
  img_path: /home/scv6267/run/geotransformer_color/image/
  root: /home/scv6267/run/geotransformer_color/Geotransformer_implicit_color/data/3DMatch/data/
  tdmatch_pth_path: ''
  pri3d_pth_path: /home/scv6267/run/geotransformer_color/checkpoint5.pth

  benchmark: 3DLoMatch
  window_size: 5
  img_num: 2
  init_mode: pri3d
  overlap_threshold: 0.5
  image_feature: True
  node_overlap: False
  debug: 0
  quaternion: False
  num_layers: 4
  in_points_dim: 3
  first_feats_dim: 256
  gnn_feats_dim: 512
  final_feats_dim: 32
  first_subsampling_dl: 0.025
  in_feats_dim: 129
  conv_radius: 2.5
  deform_radius: 5.0
  num_kernel_points: 15
  KP_extent: 2.0
  KP_influence: linear
  aggregation_mode: sum
  fixed_kernel_points: center
  use_batch_norm: True
  batch_norm_momentum: 0.02
  deformable: False
  modulated: False

overlap_attention_module:
  dgcnn_k: 10
  num_head: 4
  nets: ['self','cross','self']

loss:
  pos_margin: 0.1
  neg_margin: 1.4
  log_scale: 24
  pos_radius: 0.0375
  safe_radius: 0.1
  overlap_radius: 0.0375
  matchability_radius: 0.05
  w_circle_loss: 1.0
  w_overlap_loss: 1.0
  w_saliency_loss: 0.0
  max_points: 256

optimiser:
  optimizer: SGD
  max_epoch: 150
  lr: 0.005
  weight_decay: 0.000001
  momentum: 0.98
  scheduler: ExpLR
  scheduler_gamma: 0.95
  scheduler_freq: 1
  iter_size: 1

dataset:
  batch_size: 1
  num_workers: 10
  augment_noise: 0.005
  train_info: configs/indoor/train_info.pkl
  val_info: configs/indoor/val_info.pkl

demo:
  src_pcd: assets/cloud_bin_21.pth
  tgt_pcd: assets/cloud_bin_34.pth
  n_points: 1000
