misc:
  exp_dir: indoor
  mode: train
  gpu_mode: True
  verbose: True
  verbose_freq: 100
  snapshot_freq: 1
  pretrain: ''
    #'/home/lab507/yjl/OverlapPredator-my/snapshot/image_featuremodel__epoch_2.pth'
  #'/home/lab507/yjl/overlap_result/Quaternion_False_image_True_nodeverlap_False_2021-11-03-13:16/model__epoch_5.pth'
  #'/home/lab507/yjl/overlap_result/Quaternion_False_image_False_nodeverlap_False_2021-11-02-06:47/model__epoch_5.pth'
  #''/home/lab507/yjl/overlap_result/Quaternion_False_image_False_nodeverlap_False_2021-11-02-06:47/model__epoch_5.pth'
  #'/home/lab507/yjl/overlap_result/Quaternion_False_image_False_nodeverlap_False_2021-11-01-15:30/model__epoch_4.pth'


model:
  overlap_threshold: 0.5
  debug: 0
  image_feature: True
  node_overlap: False
  quaternion: False
  num_layers: 4
  in_points_dim: 3
  first_feats_dim: 128
  final_feats_dim: 32
  first_subsampling_dl: 0.025
  in_feats_dim: 129
  conv_radius: 2.5
  deform_radius: 5.0
  num_kernel_points: 15
  KP_extent: 2.0
  KP_influence: linear
  aggregation_mode: sum
  fixed_kernel_points: center
  use_batch_norm: True
  batch_norm_momentum: 0.02
  deformable: False
  modulated: False

overlap_attention_module:
  gnn_feats_dim: 256
  dgcnn_k: 10
  num_head: 4
  nets: ['self','cross','self']

loss:
  pos_margin: 0.1
  neg_margin: 1.4
  log_scale: 24
  pos_radius: 0.0375
  safe_radius: 0.1
  overlap_radius: 0.0375
  matchability_radius: 0.05
  w_circle_loss: 1.0
  w_overlap_loss: 1.0
  w_saliency_loss: 0.0
  max_points: 256

optimiser:
  optimizer: ADAM
  max_epoch: 80
  lr: 0.0003
  weight_decay: 0.000001
  momentum: 0.98
  scheduler: ExpLR
  scheduler_gamma: 0.95
  scheduler_freq: 1
  iter_size: 1

dataset:
  dataset: indoor
  benchmark: 3DMatch
  img_path: /home/lab507/data/3DMATCH/image
  #/home/mindspore/3dmatch/dataset/images
  root: /home/lab507/yjl/OverlapPredator_2/data/indoor
  batch_size: 1
  num_workers: 12
  augment_noise: 0.005
  train_info: configs/indoor/train_info.pkl
  val_info: configs/indoor/val_info.pkl

demo:
  src_pcd: assets/cloud_bin_21.pth
  tgt_pcd: assets/cloud_bin_34.pth
  n_points: 1000
